name: 'Run codenarc (Static Analysis for Groovy) with reviewdog'
description: '🐶 Run codenarc with reviewdog on pull requests to improve code review experience.'
author: 'luiszimmermann'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Parameters for codenarc ###
  report:
    description: '-report parameter of codenarc CLI.'
    default: 'compact:stdout'  
  rulesetfiles:
    description: '-rulesetfiles parameter of codenarc CLI. (This can be a single file path, or multiple paths separated by commas.)'
    default: 'rulesets/basic.xml'
runs:
  using: 'docker'
  image: 'docker://docker.io/asaasdev/codenarc:v2.1.0-beta'

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
