name: 'Run codenarc (Static Analysis for Groovy) with reviewdog'
description: '🐶 Run codenarc with reviewdog on pull requests to improve code review experience.'
author: 'luiszimmermann'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
    required: false
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
    required: false
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: false
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
    required: false
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
    required: false
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
    required: false
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
    required: false
  ### Parameters for codenarc ###
  report:
    description: '-report parameter of codenarc CLI.'
    default: 'compact:stdout'
    required: false
  rulesetfiles:
    description: '-rulesetfiles parameter of codenarc CLI. (This can be a single file path, or multiple paths separated by commas.)'
    default: 'rulesets/basic.xml'
    required: false
  grails_version:
    description: 'Specify version of grails to determine rulesets.'
    default: '2'
    required: false
runs:
  using: 'docker'
  image: 'docker://docker.io/asaasdev/codenarc:2.2.0'
  args:
  - >
    sh -c '
    DEFAULT_RULESETFILES="rulesets/basic.xml";
    if [ "${{ inputs.grails_version }}" = "2" ]; then
      GRAILS_RULESET="rulesets/grails2.xml";
    else
      GRAILS_RULESET="rulesets/grails4.xml";
    fi;
    
    RULESETFILES="$DEFAULT_RULESETFILES,$GRAILS_RULESET,${{ inputs.rulesetfiles }}";

    export INPUT_RULESETFILES="$RULESETFILES";

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
